# Generated by Django 4.2 on 2023-04-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Street', 'verbose_name_plural': 'Streets'},
        ),
    ]
