# Generated by Django 4.2 on 2023-04-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_city_options_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='shop_name',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='name',
            new_name='street_name',
        ),
    ]
